# This is a basic workflow to help you get started with Actions
name: Dropbox download
on:
  push:
     branches: 
      - Dropbox-refrence
  schedule:
   - cron: 0 1 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: Dropbox-refrence
      - name: "Download form dropbox"
        run: |
          wget -O excelmakesbelhappypack.7z "https://www.dropbox.com/s/yy6v60trvkgvyef/excelmakesbelhappypack.7z?dl=1" --no-verbose
          file excelmakesbelhappypack.7z
          sudo apt install p7zip
          mkdir /tmp/archive
          7z x excelmakesbelhappypack.7z -o/tmp/archive -aoa
          rsync -avh /tmp/archive/ . --force --delete --exclude='.git/' --exclude='README.md' --exclude='.gitignore' --exclude='.github/'
      - name: Commit to repository
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -am "Dropbox downlaod by bot "
          git push
      
